SELECT A.FECHA, SUM(B.CANTIDAD* B.PRECIO) AS FACTURACION
FROM facturas A
INNER JOIN items B
ON A.NUMERO = B.NUMERO
WHERE A.FECHA ='2023-07-02'
GROUP BY A.FECHA;

CALL sp_venta('2023-07-02', 100, 100);

SELECT year(A.FECHA), ceil(SUM(A.IMPUESTO * B.CANTIDAD * B.PRECIO)) AS RESULTADO
FROM facturas A
INNER JOIN items B
ON A.NUMERO = B.NUMERO
WHERE year(A.FECHA) = 2023
GROUP BY year(A.FECHA);

SELECT COUNT(*) FROM productos;