SELECT f_cliente_aleatorio();
SELECT f_producto_aleatorio();
SELECT f_vendedor_aleatorio();

SELECT MAX(NUMERO)  + 1 FROM facturas;

CALL sp_venta('2023-07-02', 5, 100);
SELECT * FROM facturas
WHERE YEAR(FECHA) = 2023;
SELECT MAX(NUMERO) FROM facturas;

SELECT COUNT(*) FROM facturas;

SELECT NUMERO FROM facturas ORDER BY NUMERO DESC LIMIT 8800;

CREATE TABLE facturas(
NUMERO INT NOT NULL,
FECHA DATE,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY(NUMERO),
FOREIGN KEY (DNI) REFERENCES clientes(DNI),
FOREIGN KEY(MATRICULA) REFERENCES vendedores(MATRICULA)
);


CREATE TABLE items(
NUMERO INT NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY(NUMERO, CODIGO),
FOREIGN KEY(NUMERO) REFERENCES facturas(NUMERO),
FOREIGN KEY(CODIGO) REFERENCES productos(CODIGO)
);

INSERT INTO items
SELECT NUMERO, CODIGO_DEL_PRODUCTO AS CODIGO,
CANTIDAD, PRECIO FROM jugos_ventas.items_facturas;

INSERT INTO facturas
SELECT NUMERO, FECHA_VENTA AS FECHA,
DNI, MATRICULA, IMPUESTO 
FROM jugos_ventas.facturas;