CREATE TABLE tb_identificación(
ID INT AUTO_INCREMENT NOT NULL,
DESCRIPCION VARCHAR(50) NULL,
PRIMARY KEY(ID)
);

SELECT * FROM tb_identificación;

INSERT 	INTO tb_identificación(DESCRIPCION)
VALUES 
(
'Cliente A'
);

INSERT 	INTO tb_identificación(DESCRIPCION)
VALUES 
(
'Cliente B'
);

INSERT 	INTO tb_identificación(DESCRIPCION)
VALUES 
(
'Cliente C'
);

INSERT 	INTO tb_identificación(DESCRIPCION)
VALUES 
(
'Cliente D'
);

INSERT 	INTO tb_identificación(DESCRIPCION)
VALUES 
(
'Cliente E'
);

INSERT 	INTO tb_identificación(DESCRIPCION)
VALUES 
(
'Cliente F'
);

INSERT 	INTO tb_identificación(DESCRIPCION)
VALUES 
(
'Cliente I'
);

INSERT 	INTO tb_identificación(ID, DESCRIPCION)
VALUES 
(
100,
'Cliente G'
);

DELETE FROM tb_identificación WHERE ID = 6;


CREATE TABLE TAB_IDENTITY2 (ID INT AUTO_INCREMENT, DESCRIPTOR VARCHAR(20), PRIMARY KEY(ID));
INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE1');
INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE2');
INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE3');
INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE4');
DELETE FROM TAB_IDENTITY2 WHERE ID = 3;
INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE6');
INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE7');
DELETE FROM TAB_IDENTITY2 WHERE ID = 2;

SELECT * FROM tab_identity2;

