-- EDAD DE LOS CLIENTES

SELECT 
    DNI,
    EDAD,
    FECHA_NACIMIENTO,
    TIMESTAMPDIFF(YEAR,
        FECHA_NACIMIENTO,
        NOW()) AS ANOS
FROM
    tb_clientes;

DELIMITER //

CREATE TRIGGER TG_EDAD_CLIENTES_INSERT
BEFORE INSERT ON tb_clientes
FOR EACH ROW BEGIN
	SET NEW.EDAD = TIMESTAMPDIFF(YEAR, FECHA_NACIMIENTO,NOW());

END //