CREATE DEFINER=`root`@`localhost` PROCEDURE `variables2`()
BEGIN
DECLARE v VARCHAR(30) DEFAULT 'Caracteres';
DECLARE n INTEGER DEFAULT 564;
DECLARE decima DECIMAL(5,3) DEFAULT 89.765;
DECLARE f DATE DEFAULT '2023-09-25';
DECLARE ts TIMESTAMP DEFAULT current_timestamp();
SELECT v;
SELECT n;
SELECT decima;
SELECT f;
SELECT ts;
END