SELECT * FROM facturas;
SELECT * FROM items_facturas;

-- primero: unir las tablas de facturas e items facturas

SELECT F.DNI, F.FECHA_VENTA, IFa.CANTIDAD 
FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

-- EL INFORME DE LA VENTA DEVOLVERLA POR DÍA Y AÑO

SELECT F.DNI, date_format(F.FECHA_VENTA, '%m/%Y') AS MES_AÑO, IFa.CANTIDAD 
FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

-- ahora queremos hacer una consulta de las ventas al cliente por mes
-- CANTIDAD DE VENTAS POR MES PARA CADA CLIENTE

SELECT F.DNI, date_format(F.FECHA_VENTA, '%m/%Y') AS MES_AÑO, 
sum(IFa.CANTIDAD ) AS CANTIDAD_VENDIDAS 
FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
GROUP BY F.DNI, MES_AÑO;

-- LISTADO DE VENTAS INVÁLIDAS

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0;

-- LIMITE DE VENTAS POR CLIENTE VOLUMEN EN DECILITROS
-- ver lo que hay en la tabla de clientes
SELECT DNI, NOMBRE, VOLUMEN_DE_COMPRA  FROM tabla_de_clientes;

-- luego hacemos un inner join con facturas, clientes e items facturas pasando el volumen a litros
SELECT F.DNI, TC.NOMBRE, date_format(F.FECHA_VENTA, '%m/%Y') AS MES_AÑO, 
sum(IFa.CANTIDAD ) AS CANTIDAD_VENDIDAS, max(TC.VOLUMEN_DE_COMPRA)/10 AS VOLUMEN_MAXIMO
FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN
tabla_de_clientes TC 
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, MES_AÑO;

-- luego, calculamos la diferencia entre las cantidades vendidas con el volumen máximo
-- usando la consulta de arriba como subconsulta
SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDAS - A.VOLUMEN_MAXIMO AS DIFERENCIA
FROM(
SELECT F.DNI, TC.NOMBRE, date_format(F.FECHA_VENTA, '%m/%Y') AS MES_AÑO, 
sum(IFa.CANTIDAD ) AS CANTIDAD_VENDIDAS, max(TC.VOLUMEN_DE_COMPRA)/10 AS VOLUMEN_MAXIMO
FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN
tabla_de_clientes TC 
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, MES_AÑO) A;

-- por último, agregamos un case para categorizar aquellas que son válidas y no válidas
SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDAS - A.VOLUMEN_MAXIMO AS DIFERENCIA,
CASE
	WHEN A.CANTIDAD_VENDIDAS - A.VOLUMEN_MAXIMO <= 0 THEN 'Venta válida'
    ELSE 'Venta inválida'
END AS STATUS_VENTA
FROM(
SELECT F.DNI, TC.NOMBRE, date_format(F.FECHA_VENTA, '%m/%Y') AS MES_AÑO, 
sum(IFa.CANTIDAD ) AS CANTIDAD_VENDIDAS, max(TC.VOLUMEN_DE_COMPRA)/10 AS VOLUMEN_MAXIMO
FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN
tabla_de_clientes TC 
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, MES_AÑO) A;

-- VENTAS INVÁLIDAS DEL 2018

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0 AND ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) > 50
AND A.MES_AÑO LIKE '%2018' ;
