SELECT * FROM tabla_de_productos;
-- clasificar los productos por ser baratos o caros

SELECT NOMBRE_DEL_PRODUCTO, PRECIO_DE_LISTA,
CASE
	 WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
	 WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'ASEQUIBLE'
     ELSE 'BARATO'
END AS PRECIO
FROM tabla_de_productos;

SELECT ENVASE, SABOR,
CASE
	 WHEN PRECIO_DE_LISTA >= 12 THEN 'Costoso'
	 WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'Asequible'
     ELSE 'Barato'
END AS PRECIO, MIN(PRECIO_DE_LISTA) AS PRECIO_MINIMO
FROM tabla_de_productos
WHERE TAMANO = '700 ml'
GROUP BY ENVASE, SABOR, PRECIO
ORDER BY ENVASE;

SELECT NOMBRE, FECHA_DE_NACIMIENTO, 
CASE
	WHEN YEAR(FECHA_DE_NACIMIENTO) < 1990 THEN 'Viejos'
    WHEN YEAR(FECHA_DE_NACIMIENTO) >= 1990 AND YEAR(FECHA_DE_NACIMIENTO) < 1995 THEN 'Jovenes'
    ELSE 'Niños'
END AS EDAD_CAT
FROM tabla_de_clientes;
