SELECT * FROM tabla_de_vendedores;
SELECT * FROM facturas;

-- INNER JOIN

SELECT * FROM tabla_de_vendedores A 
INNER JOIN
facturas B
ON A.MATRICULA = B.MATRICULA;

SELECT A.NOMBRE, B.MATRICULA, COUNT(*) FROM tabla_de_vendedores A 
INNER JOIN
facturas B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.NOMBRE, B.MATRICULA;

-- CROSS JOIN FORMA ANTIGUA

SELECT A.NOMBRE, B.MATRICULA, COUNT(*) 
FROM tabla_de_vendedores A, facturas B
WHERE A.MATRICULA = B.MATRICULA
GROUP BY A.NOMBRE, B.MATRICULA;

SELECT * FROM items_facturas;
SELECT * FROM facturas;

SELECT YEAR(FECHA_VENTA), SUM(CANTIDAD * PRECIO) AS FACTURACION
FROM facturas A
INNER JOIN
items_facturas B
ON A.NUMERO = B.NUMERO
GROUP BY YEAR(FECHA_VENTA);


